### PR TITLE
fix: respond to 404 errors when checking releases, and fall back to tags

### LINKED ISSUE #158: Swallowed error if there are fewer than 11 pages of tags
In the [`getRelease`](https://github.com/GoogleCloudPlatform/wombat-dressing-room/blob/00351e9f9aa38336fd78ee53a614ec2295d23991/packages/server/src/lib/github.ts#L83) method, an error is thrown if there is any error from the github API. However, under certain circumstances, this error ends up being swallowed in [`enforceMatchingRelease`](https://github.com/GoogleCloudPlatform/wombat-dressing-room/blob/00351e9f9aa38336fd78ee53a614ec2295d23991/packages/server/src/lib/write-package.ts#L303) and reported as "unknown error" which makes debugging this failure case difficult.

I found this while writing test cases for a case where no matching tag exists. The code does not know/check how many pages of tags exist on GitHub. It will always try to check the first 11 pages of tags. In the tests, the API is mocked, so it makes sense that if you do not mock out all 11 pages of responses, you will get an error in the test as you are trying to make an API call that has no mocked response. Even in this case though, the error should be reported as is rather than being swallowed and showing "unknown error"

It should also be verified that this does not cause a problem in production. If a project only has 4 pages of tags, then this method should not throw an error when it tries to search pages 5-11, it should simply report no matching tags found if it exhausts the list of existing tags.

#### Environment details

  - OS:
  - Node.js version:
  - npm version:
  - `wombat-dressing-room` version: 1.1

#### Steps to reproduce

  1. Create a test case for a release-backed token where the matching tag you are looking for does not exist in the list of tags on GitHub. You would expect this test case to report a 400 error and report that the matching tag was not found.
  2. Do not provide all 11 pages of responses from the mocked GitHub API. Instead of seeing the 400 error you would expect, you'll see a 500 error and "unknown error" message instead of something useful.

### PR DESCRIPTION
**Pull request by maribethb**
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/GoogleCloudPlatform/wombat-dressing-room/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #158 

1. Adds a try/catch around the entire check to getReleaseForTags. If this fails for any reason then we will fall back to checking the tags.
2. Handles the 404 case for a release cleanly. The previous code was wrong because I assumed that the API used would return a `code` 404 and an empty response if the release was missing, similar to what happens if you call the GitHub API directly with `curl`. However, this client library we're using (which is not the standard one) actually returns an error object for this case. Unfortunately I could not find any definitions for the type of Error object they're using, but after trial and error we determined the error does have a property called `statusCode` that we can check. If it's 404 then we just continue to the next tag, if it's another error then we'll throw the error, but it will be caught by step 1 and we'll fall back to tags.
3. Updated all of the tests to use `replyWithError` to more closely match how the API behaves in reality.
4. Added a test for the case where we get a non-404 error from the getReleaseForTags call.
5. Fixed a problem with the error messages in `write-message`. If this method catches an error that isn't a `WombatServerError` then it would just say "unknown error." Now, it can handle either `WombatServerError` or just regular `Error` (which has a `message` property not a `statusMessage` property) but still returns an error with the same shape (before, it was just an object that had the same properties as WombatSeverError, now it will be an actual instance of it). I tested this change by causing a generic error by not providing all of the mocked API responses to `nock` in a test. Previously, the error message would be a cryptic "unknown error" and now the error actually contains the useful message from `nock`. This isn't directly related to the core issue I was facing but it made it easier to debug after I fixed this.

I tested this change by actually using this GitHub client library in a separate test program and observing it worked the way I wanted it to. See [this gist](https://gist.github.com/maribethb/3c128751b83d3f65c081a47682c23f56) which I invoked using `node index.js` which actually performs the GH API call (instead of relying on unit tests with mocked API responses). So I am reasonably confident this change works as intended now.

### CODE REVIEW

File: packages/server/src/lib/write-package.ts [hunk 1]
```diff
@@ -298,13 +298,14 @@ async function enforceMatchingRelease(
...
       throw new WombatServerError(msg, 400);
     }
-  } catch (_err) {
-    // TODO(#158): This can swallow some errors that do have messages
-    const err = _err as {statusMessage: string; statusCode: number};
-    if (err.statusCode && err.statusMessage) throw err;
-    err.statusCode = 500;
-    err.statusMessage = 'unknown error';
-    throw err;
+  } catch (err) {
```
Comment (bcoe) [inline packages/server/src/lib/write-package.ts:301]: I'm glad that you addressed this TODO while you were at it.

**Review by bcoe — APPROVED** [review]
